# Generated by Django 5.2 on 2025-04-22 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ONGOING', max_length=20)),
                ('fen_position', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('user_color', models.CharField(default='white', max_length=5)),
                ('ai_strength', models.IntegerField(default=15)),
                ('in_opening_book', models.BooleanField(default=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('move_uci', models.CharField(max_length=10)),
                ('move_san', models.CharField(max_length=10)),
                ('position_before', models.CharField(max_length=100)),
                ('position_after', models.CharField(max_length=100)),
                ('player', models.CharField(max_length=10)),
                ('eval_score', models.FloatField(blank=True, null=True)),
                ('is_mistake', models.BooleanField(default=False)),
                ('quality', models.CharField(choices=[('best', 'Best Move'), ('excellent', 'Excellent Move'), ('good', 'Good Move'), ('inaccuracy', 'Inaccuracy'), ('mistake', 'Mistake'), ('blunder', 'Blunder'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('improvement_suggestion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='chess_app.game')),
            ],
            options={
                'ordering': ['move_number'],
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eco_code', models.CharField(blank=True, max_length=10, null=True)),
                ('pgn_moves', models.TextField()),
                ('description', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
                ('is_popular', models.BooleanField(default=False)),
                ('for_white', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('main_line', models.TextField(blank=True, null=True)),
                ('parent_opening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='chess_app.opening')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_app.opening'),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fen_position', models.CharField(max_length=100)),
                ('solution_moves', models.TextField()),
                ('difficulty', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Easy'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='chess_app.opening')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_rating', models.IntegerField(default=1200)),
                ('games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen_position', models.CharField(max_length=100)),
                ('move_san', models.CharField(blank=True, max_length=10, null=True)),
                ('move_number', models.IntegerField()),
                ('annotation', models.TextField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='chess_app.opening')),
            ],
            options={
                'ordering': ['opening', 'move_number'],
                'unique_together': {('opening', 'fen_position')},
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('solved_date', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_app.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('mastery_level', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('avg_accuracy', models.FloatField(default=0.0)),
                ('best_accuracy', models.FloatField(default=0.0)),
                ('common_mistakes', models.TextField(blank=True, null=True)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_app.opening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'opening')},
            },
        ),
    ]
