# Generated by Django 5.2 on 2025-05-24 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('PGN', 'PGN Upload'), ('LICHESS', 'Lichess'), ('CHESS_COM', 'Chess.com')], max_length=50)),
                ('source_identifier', models.CharField(blank=True, help_text='Username for chess platforms or filename for PGN', max_length=255)),
                ('total_games', models.IntegerField(default=0)),
                ('avg_mistakes', models.FloatField(default=0.0)),
                ('avg_blunders', models.FloatField(default=0.0)),
                ('avg_centipawn_loss', models.FloatField(default=0.0)),
                ('common_openings', models.JSONField(default=dict, help_text='Most commonly played openings and their statistics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('key_ideas', models.JSONField()),
                ('pitfalls', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_app.gameanalysis')),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_app.opening')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
