# Generated by Django 5.2 on 2025-05-29 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('move_uci', models.CharField(max_length=10)),
                ('move_san', models.CharField(max_length=10)),
                ('position_before', models.CharField(max_length=100)),
                ('position_after', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
                ('is_critical', models.BooleanField(default=False)),
                ('parent_move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='chess_app.lessonmove')),
            ],
            options={
                'ordering': ['move_number'],
            },
        ),
        migrations.CreateModel(
            name='AlternativeMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_uci', models.CharField(max_length=10)),
                ('move_san', models.CharField(max_length=10)),
                ('explanation', models.TextField()),
                ('evaluation', models.CharField(max_length=20)),
                ('main_move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='chess_app.lessonmove')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='chess_app.opening')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lessonmove',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='chess_app.openinglesson'),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('total_moves', models.IntegerField()),
                ('correct_moves', models.IntegerField()),
                ('time_taken', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_app.openinglesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoveReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easiness_factor', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=1)),
                ('repetitions', models.IntegerField(default=0)),
                ('last_review', models.DateTimeField(auto_now=True)),
                ('next_review', models.DateTimeField()),
                ('quality', models.IntegerField(default=0)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_app.lessonmove')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'move')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lessonmove',
            unique_together={('lesson', 'move_number', 'parent_move')},
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves_completed', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('current_move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chess_app.lessonmove')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_app.openinglesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
