# Generated by Django 5.2 on 2025-06-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0002_lessonmove_alternativemove_openinglesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmove',
            name='black_reply',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lessonmove',
            name='prompt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lessonmove',
            name='quiz_choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonmove',
            name='quiz_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
